### ISSUE TITLE
CustomProperty value field

### ISSUE THREAD

**Issue by drichelson** [launchdarkly/api-client-go#1]
Regarding [this part of the spec](https://github.com/launchdarkly/ld-openapi/blob/39c6eab78d5d0b78b4d11652e1ec047204da8568/spec/definitions.yaml#L751) :
```yaml
CustomPropertyValues:
  type: array
  description: Values for this property.
  items:
    type: string
  example: ["Value 1", "Value 2"]
```

I would expect an array of strings here:  https://github.com/launchdarkly/api-client-go/blob/3cb23d7484adf383cd429b1c8b0340f705806230/custom_property.go#L14-L20

It looks like the reference [here](https://github.com/launchdarkly/ld-openapi/blob/39c6eab78d5d0b78b4d11652e1ec047204da8568/spec/definitions.yaml#L748) isn't working as expected

Another question: Are custom properties other than strings allowed?
